### ISSUE TITLE
Plugin no longer has entries for 'total_consumption' and 'current_consumption'

### ISSUE THREAD

**Issue by ChrisHammond56** [bigbadblunt/homeassistant-lightwave2#55]
I have HASS OS 7.0 and Core 2021.10.0 installed. I had need to uninstall and reinstall the Lightwave v2 plugin. Everything went smoothly, including the new additions LED and LOCK. However, I noticed that none of the sensors are imported as Entities. I used to have Entities for total and current consumption (Watts) 

Using the LW app. I can see all the switches/lights and 'power adapter module' with all the current and total consumption. I can also the LOCK and LED status, so my assumption here is that the LinkPlus is working fine with the devices.

In the logs I get the following error:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/lightwave2/sensor.py:14
Integration: Lightwave v2 (Smart Series) custom component (documentation)
First occurred: 12:09:08 (1 occurrences)
Last logged: 12:09:08

Error setting up entry me@mysite.com for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 128, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 149, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 532, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 537, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/lightwave2/sensor.py", line 14, in <module>
    SensorEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'entity_category'

This to me is saying that the sensor has an issue and this may be why the 'consumption' Entities are not loaded?

**Comment by bigbadblunt** [comment]
Can you upgrade to at least HA 2021.11 and see if that fixes it?

**Comment by ChrisHammond56** [comment]
Unfortunately I cannot. I also use the SkyQ plugin, and upgrading past 2021.10.0 breaks that plugin. I could snapshot my install and try the upgrade to see if that fixes the Lightwave plugin I suppose.

**Comment by ChrisHammond56** [comment]
Ok, so I tried 2021.11.0 and the consumption is back :) I have also noticed that SkyQ plugin is still working. So it must break somewhere between 2021.11.0 and 2021.12.3. However, as it is working again, I will keep the core as -is. I will close this issue as no-issue, but thanks for the pointer.

**Comment by bigbadblunt** [comment]
SkyQ works on 2021.12.0 for me.
