### ISSUE TITLE
API error using set_led_rgb

### ISSUE THREAD

**Issue by jbilling9** [bigbadblunt/homeassistant-lightwave2#49]
API error 'LWRF2Light' object has no attribute 'ledrgb' when trying to use set_led_rgb.
It occurs from v3.5.3 to v3.5.6, working correctly on v3.5.1

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/lightwave2/light.py:150
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:20:59 (4 occurrences)
Last logged: 12:21:01

[140466948796576] 'LWRF2Light' object has no attribute 'ledrgb'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/lightwave2/__init__.py", line 36, in service_handle_led
    await ent.async_set_rgb(led_rgb=rgb)
  File "/config/custom_components/lightwave2/light.py", line 150, in async_set_rgb
    await self._lwlink.async_set_led_rgb_by_featureset_id(self._featureset_id, self.ledrgb)
AttributeError: 'LWRF2Light' object has no attribute 'ledrgb'

**Comment by bigbadblunt** [comment]
Should be fixed in the latest version.

All of the LEDs are now exposed as their own entities, so you can set the LED colour that way. I will be removing the set_led_rgb service call at some point in the future to simplify the code, so you'll need to move over to that way of doing it (using `light.turn_on` with an `rgb_color` parameter).

But for now I've fixed the service call.

**Comment by jbilling9** [comment]
That was quick! All working again, thanks.

Ah that makes sense. I've tested the new way of doing it and it seems simple enough, thanks again!
